### ISSUE TITLE
Open in editor

### ISSUE THREAD

**Issue by kosirm** [thegoodideaco/vue-d3-workshop#1]
Hi, first of all, thank you so much for your workshops, which were for me the doors to enter vue-d3 world :) I have one question which is not related to workshop... what are the steps to achieve "open in editor" action (if I click "Open" button in browser, the source file is opened in vscode, which is something what I would like to implement). Could you explain how you do this?

**Comment by thegoodideaco** [comment]
Sure, all you need to do is use something like axios to run a get on a specific url, take a look at the network tab when you open via the editor. components have a _file property when in dev mode
